admin:
  - 123123
  - 123
telegram_token: "12344321:QWERTYqwertyDeusExMachina"
unsplash_token: "QWERTYqwertyPlantExMachina"

green_list:
  - "plant"
  - "grass"
  - "tree"
  - "fruit"
  - "flower"
  - "leaf"
  - "bush"

green_list_random:
  min: 1
  max: 5

landscape_list:
  - "mountain"
  - "river"
  - "lake"
  - "forest"
  - "desert"
  - "ocean"
  - "valley"
  - "plain"
  - "island"
  - "waterfall"

landscape_list_random:
  min: 1
  max: 2

license: "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n                   Version 2, December 2004\n\nCopyright (C) 2004 Sam Hocevar <sam@hocevar.net>\n\nEveryone is permitted to copy and distribute verbatim or modified\ncopies of this license document, and changing it is allowed as long\nas the name is changed.\n\n           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n\n 0. You just DO WHAT THE FUCK YOU WANT TO.\n"
